-- Migration 007: Make matches.id and teams.id identity columns
-- This allows inserting without providing an explicit ID.

ALTER TABLE public.matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Sync sequences
DO $$
DECLARE
    m_id INTEGER;
    t_id INTEGER;
BEGIN
    SELECT MAX(id) INTO m_id FROM public.matches;
    IF m_id IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.matches ALTER COLUMN id RESTART WITH ' || (m_id + 1);
    END IF;
    
    SELECT MAX(id) INTO t_id FROM public.teams;
    IF t_id IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.teams ALTER COLUMN id RESTART WITH ' || (t_id + 1);
    END IF;
END $$;
